// <auto-generated />
using IndustrailEquipment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IndustrailEquipment.Migrations
{
    [DbContext(typeof(IndustrailEquipmentContext))]
    [Migration("20220831023230_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IndustrailEquipment.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            Hours = 302,
                            Name = "AGV_01",
                            SerialNumber = "2867654",
                            Status = "Running"
                        },
                        new
                        {
                            MachineId = 2,
                            Hours = 246,
                            Name = "AGV_02",
                            SerialNumber = "2658392",
                            Status = "Faulted"
                        },
                        new
                        {
                            MachineId = 3,
                            Hours = 432,
                            Name = "AGV_03",
                            SerialNumber = "9867232",
                            Status = "Idle"
                        },
                        new
                        {
                            MachineId = 4,
                            Hours = 654,
                            Name = "AGV_04",
                            SerialNumber = "2837892",
                            Status = "Running"
                        },
                        new
                        {
                            MachineId = 5,
                            Hours = 123,
                            Name = "AGV_05",
                            SerialNumber = "2839404",
                            Status = "Running"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
